// NEWLINE-TIMEOUT: 10
// ASSERT-SUCC: Dynamic application test started
// ASSERT-SUCC: DSO_LOAD soname=libc.so.1
// ASSERT-SUCC: hello dynamic app
// ASSERT-SUCC: argv0=/apps/hello/app.elf
// ASSERT-SUCC: auxv: AT_PHDR ok
// ASSERT-SUCC: APP_LAUNCHED handle=.* path=/apps/hello/app.elf
// ASSERT-SUCC: APP_INIT_COMPLETE handle=.*
// ASSERT-SUCC: APP_REAP handle=.* private_images=1 imported_dsos=1
// ASSERT-SUCC: DSO_REUSE soname=libc.so.1
// ASSERT-SUCC: Dynamic application test ended
// ASSERT-FAIL: Backtrace in Panic.*
// ASSERT-FAIL: ASSERTION FAILED.*

#![no_main]
#![no_std]
#![feature(custom_test_frameworks)]
#![test_runner(dynamic_test_runner)]
#![reexport_test_harness_main = "dynamic_test_main"]
#![feature(c_size_t)]

//! C29 vertical MVP: launch a real Thumb PIE dynamic application through the
//! full kernel path — VFS snapshot, dependency closure, `libc.so.1` load,
//! ARM32 NOW relocation, thread entry, `scrt1`/`librs` startup, application
//! exit and deferred reaping — on `qemu_mps2_an385` (§18).
//!
//! The artifacts (`apps/example/dynamic/hello` and `librs:libc`) are read from
//! the host through semihosting and seeded into the kernel's tmpfs at fixed
//! paths before the application service starts, so the whole link runs over
//! the real VFS `ElfReader`/`SystemDsoRegistry` path.

extern crate alloc;
extern crate rsrt;

use alloc::vec::Vec;
use blueos::application::adapters::system_paths::{SystemLibraryEntry, SystemLibraryPaths};
use blueos::application::service::ApplicationService;
use blueos_loader::LinkDomainId;
use blueos_test_macro::test;
use core::ffi::c_char;
use core::sync::atomic::{AtomicUsize, Ordering};
use librs::pthread;
use semihosting::io::{Read, Seek, SeekFrom};
use semihosting::println;

extern "C" {
    /// Absolute host path of the built hello PIE (out/<board>/bin/hello).
    static DYNAMIC_HELLO_ELF_PATH: *const c_char;
    /// Absolute host path of the built libc DSO (out/<board>/lib/liblibrs.so,
    /// SONAME `libc.so.1`).
    static LIBC_SO_1_PATH: *const c_char;
}

/// The fixed system library catalog Phase 1 resolves `DT_NEEDED` against
/// (§12.2). The runtime file at this VFS path is seeded from the host artifact
/// below.
static SYSTEM_LIBRARIES: &[SystemLibraryEntry] = &[SystemLibraryEntry {
    soname: b"libc.so.1",
    path: "/system/lib/libc.so.1",
    build_id: None,
}];
static CATALOG: SystemLibraryPaths = SystemLibraryPaths::new(SYSTEM_LIBRARIES);

/// Read a whole host file through semihosting into a heap buffer.
fn read_host_file(ptr: *const c_char) -> Vec<u8> {
    // SAFETY: the path symbol is a NUL-terminated static string generated by
    // the build from the artifact's output path.
    let path = unsafe { core::ffi::CStr::from_ptr(ptr) };
    let mut file = semihosting::fs::File::open(path).expect("open host artifact");
    let len = file.seek(SeekFrom::End(0)).expect("seek host artifact end") as usize;
    file.seek(SeekFrom::Start(0)).expect("seek host artifact start");
    let mut bytes = Vec::new();
    bytes
        .try_reserve_exact(len)
        .expect("reserve host artifact buffer");
    bytes.resize(len, 0);
    let mut filled = 0;
    while filled < len {
        let n = file.read(&mut bytes[filled..]).expect("read host artifact");
        assert!(n > 0, "host artifact short read at {filled}/{len}");
        filled += n;
    }
    bytes
}

/// Create the parent directories of `path` inside the root tmpfs, best effort
/// (already-exists errors are fine for a test fixture). Only *parents* are
/// created: the last component is the file itself.
fn mkdirs(path: &str) {
    let mut bytes = [0u8; 64];
    let mut prefix_end = 1; // skip the leading '/'
    while prefix_end < path.len() {
        let slash = match path[prefix_end..].find('/') {
            Some(at) => prefix_end + at,
            // The last component is the seeded file, not a directory.
            None => break,
        };
        let dir = &path[..slash];
        assert!(dir.len() < bytes.len(), "fixture path too deep");
        bytes[..dir.len()].copy_from_slice(dir.as_bytes());
        bytes[dir.len()] = 0;
        // SAFETY: `bytes` holds a NUL-terminated copy of `dir`.
        let rc = unsafe { blueos::vfs::syscalls::mkdir(bytes.as_ptr() as *const c_char, 0o755) };
        let _ = rc; // EEXIST is expected for repeated runs.
        prefix_end = slash + 1;
    }
}

/// Write `bytes` into a fresh VFS file at `path`.
fn seed_vfs_file(path: &str, bytes: &[u8]) {
    mkdirs(path);
    let mut path_buf = [0u8; 64];
    assert!(path.len() < path_buf.len(), "fixture path too long");
    path_buf[..path.len()].copy_from_slice(path.as_bytes());
    path_buf[path.len()] = 0;
    // SAFETY: `path_buf` holds a NUL-terminated copy of `path`; the kernel
    // syscall helpers take raw pointers by contract.
    unsafe {
        let fd = blueos::vfs::syscalls::open(
            path_buf.as_ptr() as *const c_char,
            libc::O_CREAT | libc::O_WRONLY,
            0o644,
        );
        assert!(fd >= 0, "open seeded VFS file failed: {fd}");
        let written = blueos::vfs::syscalls::write(fd, bytes.as_ptr(), bytes.len());
        assert_eq!(
            written as usize,
            bytes.len(),
            "seeded VFS file write truncated"
        );
        blueos::vfs::syscalls::close(fd);
    }
}

/// Launch the hello app and wait (bounded) for the deferred reaper to recycle
/// its slot, then assert the public state is gone. Returns the handle whose
/// generation the relaunch assertion compares against.
fn launch_and_wait(service: &ApplicationService, argc1: bool) -> blueos::application::manager::ApplicationHandle {
    let mut argv = Vec::new();
    argv.push(b"/apps/hello/app.elf".to_vec());
    if argc1 {
        argv.push(b"arg1".to_vec());
    }
    let handle = service
        .spawn("/apps/hello/app.elf", argv, Vec::new())
        .expect("spawn dynamic app");

    // Bounded poll: the reaper scans every REAPER_POLL_MILLIS and the app
    // exits within milliseconds of starting.
    static WAIT_ATOM: AtomicUsize = AtomicUsize::new(0);
    for _ in 0..600 {
        if service.manager().query(handle).is_none() {
            return handle;
        }
        let _ = blueos::sync::atomic_wait(
            &WAIT_ATOM,
            WAIT_ATOM.load(Ordering::Acquire),
            blueos::time::Tick::from_millis(50),
        );
    }
    panic!("application was not reaped within the wait bound");
}

#[test]
fn dynamic_app_vertical() {
    // Seed the immutable build-time catalog into the root tmpfs before the
    // service starts (§18.1).
    let hello = read_host_file(unsafe { DYNAMIC_HELLO_ELF_PATH });
    let libc = read_host_file(unsafe { LIBC_SO_1_PATH });
    assert!(!hello.is_empty(), "hello artifact is empty");
    assert!(!libc.is_empty(), "libc artifact is empty");
    seed_vfs_file("/apps/hello/app.elf", &hello);
    seed_vfs_file("/system/lib/libc.so.1", &libc);

    let service = ApplicationService::init(&CATALOG, LinkDomainId::new(1));

    // First launch: this link is the first loading generation for libc.so.1
    // (DSO_LOAD), the app runs its main through the shared libc, exits and is
    // reaped with its private image and its one imported libc lease.
    let first = launch_and_wait(service, true);

    // Second launch: the Ready libc instance is imported (DSO_REUSE), not
    // remapped; the slot is recycled with a bumped generation (§14.3).
    let second = launch_and_wait(service, false);
    assert_eq!(first.slot, second.slot, "slot must be recycled");
    assert_ne!(
        first.generation, second.generation,
        "generation must bump on relaunch"
    );
}

#[no_mangle]
pub fn dynamic_test_runner(tests: &[&dyn Fn()]) {
    println!("Dynamic application test started");
    println!("Running {} tests", tests.len());
    for test in tests {
        test();
    }
    println!("Dynamic application test ended");
}

#[no_mangle]
pub extern "C" fn main() -> i32 {
    pthread::register_my_posix_tcb();
    dynamic_test_main();
    0
}
