# Copyright (c) 2025 vivo Mobile Communication Co., Ltd.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import("//build/boards/${board}.gni")
import("//build/templates/build_template.gni")
import("//build/toolchain/blueos.gni")

_loader_unittest_on_qemu = false
if (defined(qemu_exe)) {
  _loader_unittest_on_qemu = qemu_exe != ""
}

group("check_loader") {
  testonly = true
  deps = [ "tests:run_loader_integration_test" ]
  if (_loader_unittest_on_qemu) {
    deps += [ ":run_loader_unittest" ]
  }
}

group("inputs") {
  testonly = true
  deps = [ "tests/inputs" ]
}

if (coverage || profile) {
  build_rust("common_cov") {
    crate_type = "rlib"
    sources = [ "tests/cov/lib.rs" ]
    deps = [
      "//external/vendor/minicov-0.3.7:minicov",
      "//external/vendor/semihosting-0.1.20:semihosting",
    ]
  }
}

build_rust("blueos_loader") {
  crate_type = "rlib"
  sources = [ "src/lib.rs" ]
  configs += [ "//build/boards/${board}:kernel_config" ]
  rustflags = [
    "--cfg",
    "target_board=\"${board}\"",
  ]
  deps = [
    "//external/vendor/goblin-0.9.3:goblin",
    "//kernel/infra:blueos_infra",
  ]
}

run_clippy("blueos_loader_clippy") {
  deps = [ ":blueos_loader" ]
}

if (_loader_unittest_on_qemu) {
  build_rust("loader_unittest") {
    testonly = true
    crate_name = "loader_unittest"
    crate_type = "bin"
    sources = [ "src/lib.rs" ]
    edition = "2021"
    deps = [
      "//external/vendor/goblin-0.9.3:goblin",
      "//kernel/infra:blueos_infra",
    ]
    rustflags = [ "--test" ]
    configs += [ "//build/boards/${board}:kernel_config" ]
    rustflags += [
      "--cfg",
      "target_board=\"${board}\"",
    ]
    deps += [
      "//external/vendor/semihosting-0.1.20:semihosting",
      "//kernel/kernel:blueos",
      "//kernel/rsrt",
      "//libc",
      "//librs",
    ]
    linker_script = default_linker_script
    proc_macro_deps = [ "//kernel/test_harness:blueos_test_macro" ]
  }

  if (defined(qemu_use_esp32_loader) && qemu_use_esp32_loader) {
    gen_esp32_qemu_runner("loader_unittest_runner") {
      testonly = true
      elf = ":loader_unittest"
      chip = "${chip}"
      bootloader = qemu_esp32_bootloader_bin
      partition_table = qemu_esp32_partition_table_bin
      qemu = qemu_exe
      machine = qemu_machine
      qemu_args = qemu_extra_args
      net_args = qemu_net_args
      block_args = qemu_block_args
      semihosting = true
    }
  } else {
    gen_qemu_runner("loader_unittest_runner") {
      testonly = true
      img = ":loader_unittest"
      qemu = qemu_exe
      machine = qemu_machine
      semihosting = true
      qemu_args = qemu_extra_args
      block_img = "loader_unittest_block.img"
      block_args = qemu_block_args
    }
  }

  run_qemu_check("run_loader_unittest") {
    testonly = true
    runner = ":loader_unittest_runner"
    if (coverage) {
      img = ":loader_unittest"
      checker = "tests/cov/lib.rs"
    } else {
      checker = "src/unittests.checker"
    }
  }

  run_clippy("loader_unittest_clippy") {
    testonly = true
    deps = [ ":loader_unittest" ]
  }
}

group("check_loader_by_clippy") {
  testonly = true
  deps = [
    ":blueos_loader_clippy",

    # ":loader_unittest_clippy",
    "tests/integration_test:loader_integration_test_clippy",
  ]
  if (coverage || profile) {
    deps += [ ":common_cov" ]
  }
}
